<a href="https://colab.research.google.com/github/ap12798/Applied_Deep_Learning/blob/main/Dense_Network_Experiment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import keras
import pandas as pd
import numpy as np

from keras.datasets import mnist
from keras.models import Sequential
from keras.layers import Dense
from keras.optimizers import SGD

In [ ]:
from seaborn import load_dataset
iris_df = load_dataset("iris")
iris_df.species = pd.Categorical(iris_df.species, categories=['setosa','versicolor','virginica'])
iris_df.head()

sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [ ]:
iris_df.tail()

sepal_length  sepal_width  petal_length  petal_width    species
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

In [ ]:
iris_df.species.value_counts()

virginica     50
versicolor    50
setosa        50
Name: species, dtype: int64

In [ ]:
iris_df.species.cat.codes.value_counts()

2    50
1    50
0    50
dtype: int64

In [ ]:
X = iris_df.drop('species', axis=1)
X.head(2)

sepal_length  sepal_width  petal_length  petal_width
0           5.1          3.5           1.4          0.2
1           4.9          3.0           1.4          0.2

In [ ]:
X=X.values
X.shape

(150, 4)

In [ ]:
y = iris_df.species.cat.codes
y.head()

0    0
1    0
2    0
3    0
4    0
dtype: int8

In [ ]:
y.tail()

145    2
146    2
147    2
148    2
149    2
dtype: int8

In [ ]:
y=y.values
y.shape

(150,)

In [ ]:
from sklearn.model_selection import train_test_split

X_train, X_valid, y_train, y_valid = train_test_split(X, y, test_size=0.25, random_state=0, stratify=y)

X_train.shape, X_valid.shape, y_train.shape, y_valid.shape

((112, 4), (38, 4), (112,), (38,))

In [ ]:
y_train[0]

1

In [ ]:
from tensorflow.keras.utils import to_categorical
n_classes = 3
y_train = to_categorical(y_train, n_classes)
y_valid = to_categorical(y_valid, n_classes)

In [ ]:
y_train.shape, y_valid.shape

((112, 3), (38, 3))

In [ ]:
y_train[0]

array([0., 1., 0.], dtype=float32)

In [ ]:
model = Sequential()
model.add(Dense(units=10, activation='relu', input_shape=(4,))) #input layer and hidden layer, so total of 3
model.add(Dense(units=8, activation='relu'))
model.add(Dense(units=6, activation='relu'))
model.add(Dense(units=3, activation='softmax'))

In [ ]:
model.summary()

Model: "sequential_2"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_8 (Dense)              (None, 10)                50        
_________________________________________________________________
dense_9 (Dense)              (None, 8)                 88        
_________________________________________________________________
dense_10 (Dense)             (None, 6)                 54        
_________________________________________________________________
dense_11 (Dense)             (None, 3)                 21        
Total params: 213
Trainable params: 213
Non-trainable params: 0
_________________________________________________________________


In [ ]:
model.compile(loss='mean_squared_error', optimizer=SGD(lr=0.01), metrics=['accuracy'])

/usr/local/lib/python3.7/dist-packages/tensorflow/python/keras/optimizer_v2/optimizer_v2.py:375: UserWarning: The `lr` argument is deprecated, use `learning_rate` instead.
  "The `lr` argument is deprecated, use `learning_rate` instead.")


In [ ]:
model.fit(X_train, y_train, batch_size=1, epochs=50, verbose=1, validation_data=(X_valid, y_valid))

Epoch 1/50
112/112 [==============================] - 14s 6ms/step - loss: 0.2160 - accuracy: 0.4985 - val_loss: 0.1813 - val_accuracy: 0.8684
Epoch 2/50
112/112 [==============================] - 0s 2ms/step - loss: 0.1804 - accuracy: 0.7127 - val_loss: 0.1627 - val_accuracy: 0.8947
Epoch 3/50
112/112 [==============================] - 0s 2ms/step - loss: 0.1629 - accuracy: 0.6758 - val_loss: 0.1518 - val_accuracy: 0.8421
Epoch 4/50
112/112 [==============================] - 0s 2ms/step - loss: 0.1578 - accuracy: 0.7029 - val_loss: 0.1407 - val_accuracy: 0.7105
Epoch 5/50
112/112 [==============================] - 0s 2ms/step - loss: 0.1527 - accuracy: 0.6913 - val_loss: 0.1334 - val_accuracy: 0.6842
Epoch 6/50
112/112 [==============================] - 0s 2ms/step - loss: 0.1287 - accuracy: 0.7392 - val_loss: 0.1267 - val_accuracy: 0.6842
Epoch 7/50
112/112 [==============================] - 0s 2ms/step - loss: 0.1216 - accuracy: 0.7380 - val_loss: 0.1218 - val_accuracy: 0.9474
Epoch

In [ ]:
model.evaluate(X_valid, y_valid)

2/2 [==============================] - 0s 8ms/step - loss: 0.1051 - accuracy: 0.6579


[0.10511653125286102, 0.6578947305679321]

In [ ]:
y_valid[0]

array([1., 0., 0.], dtype=float32)

In [ ]:
model.predict(X_valid[0].reshape(1,-1))

array([[9.8301882e-01, 1.6975494e-02, 5.5904120e-06]], dtype=float32)

##Your Turn
- Build a Dense Network using continuous features to predict customer churn
- Experiment with different size layers and different activation functions
- Think about what activation makes sense for the output layer 

In [2]:
from google.colab import files

uploaded = files.upload()

for fn in uploaded.keys():
  print('User uploaded file "{name}" with length {length} bytes'.format(
      name=fn, length=len(uploaded[fn])))

Saving churn.csv to churn.csv
User uploaded file "churn.csv" with length 720409 bytes


In [3]:
import pandas as pd
churn_df = pd.read_csv('churn.csv')
churn_df.head()

State  Account Length  Area Code  ... Intl Charge CustServ Calls  Churn?
0    PA             163        806  ...    5.673203              3   True.
1    SC              15        836  ...    2.559749              8  False.
2    MO             131        777  ...    6.254157              4  False.
3    WY              75        878  ...    1.080692              6  False.
4    WY             146        878  ...    7.134343              6   True.

[5 rows x 21 columns]

In [ ]:
churn_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 21 columns):
 #   Column          Non-Null Count  Dtype  
---  ------          --------------  -----  
 0   State           5000 non-null   object 
 1   Account Length  5000 non-null   int64  
 2   Area Code       5000 non-null   int64  
 3   Phone           5000 non-null   object 
 4   Int'l Plan      5000 non-null   object 
 5   VMail Plan      5000 non-null   object 
 6   VMail Message   5000 non-null   int64  
 7   Day Mins        5000 non-null   float64
 8   Day Calls       5000 non-null   int64  
 9   Day Charge      5000 non-null   float64
 10  Eve Mins        5000 non-null   float64
 11  Eve Calls       5000 non-null   int64  
 12  Eve Charge      5000 non-null   float64
 13  Night Mins      5000 non-null   float64
 14  Night Calls     5000 non-null   int64  
 15  Night Charge    5000 non-null   float64
 16  Intl Mins       5000 non-null   float64
 17  Intl Calls      5000 non-null   i

In [53]:
import numpy as np

cols = ['Day Mins', 'Day Charge', 'Eve Mins', 'Eve Charge', 'Night Mins', 'Night Charge', 'Intl Mins', 'Intl Charge', 'CustServ Calls', 'Churn?']
churn_data = churn_df[cols].copy()
churn_data['Churn'] = np.where(churn_data['Churn?'] =='True.', 1, 0)
churn_data.head()

Day Mins  Day Charge  Eve Mins  ...  CustServ Calls  Churn?  Churn
0   8.162204    7.579174  3.933035  ...               3   True.      1
1  10.018993    4.226289  2.325005  ...               8  False.      0
2   4.708490    4.768160  4.537466  ...               4  False.      0
3   1.268734    2.567642  2.528748  ...               6  False.      0
4   2.696177    5.908916  6.015337  ...               6   True.      1

[5 rows x 11 columns]

In [5]:
churn_data['Churn'].value_counts()

0    2502
1    2498
Name: Churn, dtype: int64

In [54]:
features = ['Day Mins', 'Day Charge', 'Eve Mins', 'Eve Charge', 'Night Mins', 'Night Charge', 'Intl Mins', 'Intl Charge', 'CustServ Calls']
target = 'Churn'

X = churn_data[features].values
y = churn_data[target].values
X.shape, y.shape

((5000, 9), (5000,))

In [55]:
from sklearn.model_selection import train_test_split

X_train, X_valid, y_train, y_valid = train_test_split(X, y, test_size=0.25, random_state=0)

X_train.shape, X_valid.shape, y_train.shape, y_valid.shape

((3750, 9), (1250, 9), (3750,), (1250,))

In [ ]:
X_train

array([[13.23664371, 11.00768366,  5.54973717, ...,  6.12155121,
         3.12411923,  3.        ],
       [ 3.64623966,  4.11254353,  2.83378984, ...,  5.58227412,
         2.96599581,  7.        ],
       [ 0.53955568,  3.66313094,  0.08811626, ...,  4.46893939,
         1.29072559,  4.        ],
       ...,
       [10.40811761,  6.20244068,  7.00614012, ...,  4.32914583,
         4.21910436,  3.        ],
       [10.0109857 ,  7.35504399,  6.7736002 , ...,  3.69210465,
         6.18139625,  4.        ],
       [ 1.65060626,  4.23125228,  4.88634033, ...,  6.5126707 ,
         3.49669159,  5.        ]])

In [ ]:
y_train

array([1, 0, 0, ..., 1, 1, 0])

Consider whether you should normalize using:
https://keras.io/api/utils/python_utils/#normalize-function

In [35]:
from tensorflow.keras.utils import normalize

normalize(X_train)

array([[0.89374987, 0.26289441, 0.2186248 , ..., 0.12158079, 0.06204847,
        0.05958332],
       [0.98711802, 0.04284844, 0.04832816, ..., 0.06559956, 0.03485462,
        0.08225984],
       [0.99738028, 0.00407683, 0.02767829, ..., 0.03376691, 0.00975261,
        0.03022364],
       ...,
       [0.99223733, 0.06884882, 0.04102862, ..., 0.02863693, 0.02790902,
        0.01984475],
       [0.99503734, 0.05134693, 0.03772445, ..., 0.01893702, 0.03170474,
        0.02051623],
       [0.99143599, 0.01818301, 0.04661129, ..., 0.07174329, 0.0385194 ,
        0.05507978]])

In [56]:
model = Sequential()
model.add(Dense(units=10, activation='relu', input_shape=(9,))) #input layer and hidden layer, so total of 3
model.add(Dense(units=8, activation='tanh'))
# model.add(Dense(units=6, activation='relu'))
model.add(Dense(units=1, activation='sigmoid'))

In [50]:
model.summary()

Model: "sequential_4"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_14 (Dense)             (None, 10)                110       
_________________________________________________________________
dense_15 (Dense)             (None, 8)                 88        
_________________________________________________________________
dense_16 (Dense)             (None, 1)                 9         
Total params: 207
Trainable params: 207
Non-trainable params: 0
_________________________________________________________________


In [57]:
model.compile(loss='mean_squared_error', optimizer=SGD(learning_rate=0.01), metrics=['accuracy'])

In [58]:
model.fit(X_train, y_train, batch_size=1, epochs=10, verbose=1, validation_data=(X_valid, y_valid))

Epoch 1/10
3750/3750 [==============================] - 7s 2ms/step - loss: 0.1725 - accuracy: 0.7536 - val_loss: 0.1314 - val_accuracy: 0.8184
Epoch 2/10
3750/3750 [==============================] - 5s 1ms/step - loss: 0.1270 - accuracy: 0.8270 - val_loss: 0.1082 - val_accuracy: 0.8608
Epoch 3/10
3750/3750 [==============================] - 5s 1ms/step - loss: 0.1097 - accuracy: 0.8529 - val_loss: 0.1035 - val_accuracy: 0.8608
Epoch 4/10
3750/3750 [==============================] - 5s 1ms/step - loss: 0.0971 - accuracy: 0.8598 - val_loss: 0.1236 - val_accuracy: 0.8184
Epoch 5/10
3750/3750 [==============================] - 5s 1ms/step - loss: 0.0962 - accuracy: 0.8718 - val_loss: 0.0857 - val_accuracy: 0.8888
Epoch 6/10
3750/3750 [==============================] - 6s 1ms/step - loss: 0.0884 - accuracy: 0.8729 - val_loss: 0.0878 - val_accuracy: 0.8848
Epoch 7/10
3750/3750 [==============================] - 5s 1ms/step - loss: 0.0858 - accuracy: 0.8800 - val_loss: 0.0844 - val_accuracy:

In [59]:
model.evaluate(X_valid, y_valid)

40/40 [==============================] - 0s 2ms/step - loss: 0.0968 - accuracy: 0.8632


[0.09679380059242249, 0.8632000088691711]

In [60]:
y_valid[0:10]

array([0, 1, 1, 0, 0, 0, 1, 0, 1, 1])

In [23]:
# model.predict(X_valid[10].reshape(1,-1))

array([[0.87091994]], dtype=float32)

In [61]:
y_pred = model.predict(X_valid)
y_pred[:10]

array([[0.00619647],
       [0.8637851 ],
       [0.94904685],
       [0.0483596 ],
       [0.13259804],
       [0.13195819],
       [0.9603261 ],
       [0.01169142],
       [0.69872326],
       [0.9527961 ]], dtype=float32)