<a href="https://colab.research.google.com/github/ap12798/Applied_Deep_Learning/blob/main/Dense_Network_Experiment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import keras
import pandas as pd
import numpy as np

from keras.datasets import mnist
from keras.models import Sequential
from keras.layers import Dense
from keras.optimizers import SGD

In [ ]:
from seaborn import load_dataset
iris_df = load_dataset("iris")
iris_df.species = pd.Categorical(iris_df.species, categories=['setosa','versicolor','virginica'])
iris_df.head()

sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [ ]:
iris_df.tail()

sepal_length  sepal_width  petal_length  petal_width    species
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

In [ ]:
iris_df.species.value_counts()

virginica     50
versicolor    50
setosa        50
Name: species, dtype: int64

In [ ]:
iris_df.species.cat.codes.value_counts()

2    50
1    50
0    50
dtype: int64

In [ ]:
X = iris_df.drop('species', axis=1)
X.head(2)

sepal_length  sepal_width  petal_length  petal_width
0           5.1          3.5           1.4          0.2
1           4.9          3.0           1.4          0.2

In [ ]:
X=X.values
X.shape

(150, 4)

In [ ]:
y = iris_df.species.cat.codes
y.head()

0    0
1    0
2    0
3    0
4    0
dtype: int8

In [ ]:
y.tail()

145    2
146    2
147    2
148    2
149    2
dtype: int8

In [ ]:
y=y.values
y.shape

(150,)

In [ ]:
from sklearn.model_selection import train_test_split

X_train, X_valid, y_train, y_valid = train_test_split(X, y, test_size=0.25, random_state=0, stratify=y)

X_train.shape, X_valid.shape, y_train.shape, y_valid.shape

((112, 4), (38, 4), (112,), (38,))

In [ ]:
y_train[0]

1

In [ ]:
n_classes = 3
y_train = keras.utils.to_categorical(y_train, n_classes)
y_valid = keras.utils.to_categorical(y_valid, n_classes)

In [ ]:
y_train.shape, y_valid.shape

((112, 3), (38, 3))

In [ ]:
y_train[0]

array([0., 1., 0.], dtype=float32)

In [ ]:
model = Sequential()
model.add(Dense(units=4, activation='relu', input_shape=(4,)))
model.add(Dense(units=3, activation='relu'))
model.add(Dense(units=2, activation='relu'))
model.add(Dense(units=3, activation='softmax'))

In [ ]:
model.summary()

Model: "sequential_4"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_14 (Dense)             (None, 4)                 20        
_________________________________________________________________
dense_15 (Dense)             (None, 3)                 15        
_________________________________________________________________
dense_16 (Dense)             (None, 2)                 8         
_________________________________________________________________
dense_17 (Dense)             (None, 3)                 9         
Total params: 52
Trainable params: 52
Non-trainable params: 0
_________________________________________________________________


In [ ]:
model.compile(loss='mean_squared_error', optimizer=SGD(lr=0.01), metrics=['accuracy'])

In [ ]:

model.fit(X_train, y_train, batch_size=1, epochs=50, verbose=1, validation_data=(X_valid, y_valid))

In [ ]:
model.evaluate(X_valid, y_valid)

2/2 [==============================] - 0s 8ms/step - loss: 0.1051 - accuracy: 0.6579


[0.10511653125286102, 0.6578947305679321]

In [ ]:
y_valid[0]

array([1., 0., 0.], dtype=float32)

In [ ]:
model.predict(X_valid[0].reshape(1,-1))

array([[0.7410781 , 0.1862702 , 0.07265177]], dtype=float32)

##Your Turn
- Build a Dense Network using continuous features to predict customer churn
- Experiment with different size layers and different activation functions
- Think about what activation makes sense for the output layer 

In [ ]:
from google.colab import files

uploaded = files.upload()

for fn in uploaded.keys():
  print('User uploaded file "{name}" with length {length} bytes'.format(
      name=fn, length=len(uploaded[fn])))

Saving churn.csv to churn.csv
User uploaded file "churn.csv" with length 969287 bytes


In [ ]:
import pandas as pd
churn_df = pd.read_csv('churn.csv')
churn_df.head()

State  Account Length  Area Code  ... Intl Charge CustServ Calls  Churn?
0    PA             163        806  ...    5.673203              3   True.
1    SC              15        836  ...    2.559749              8  False.
2    MO             131        777  ...    6.254157              4  False.
3    WY              75        878  ...    1.080692              6  False.
4    WY             146        878  ...    7.134343              6   True.

[5 rows x 21 columns]

In [ ]:
churn_df.info()

In [ ]:
import numpy as np

cols = ['Day Mins', 'Day Charge', 'Eve Mins', 'Eve Charge', 'Night Mins', 'Night Charge', 'Intl Mins', 'Intl Charge', 'CustServ Calls', 'Churn?']
churn_data = churn_df[cols].copy()
churn_data['Churn'] = np.where(churn_data['Churn?'] =='True.', 1, 0)
churn_data.head()

Day Mins  Day Charge  Eve Mins  ...  CustServ Calls  Churn?  Churn
0   8.162204    7.579174  3.933035  ...               3   True.      1
1  10.018993    4.226289  2.325005  ...               8  False.      0
2   4.708490    4.768160  4.537466  ...               4  False.      0
3   1.268734    2.567642  2.528748  ...               6  False.      0
4   2.696177    5.908916  6.015337  ...               6   True.      1

[5 rows x 11 columns]

In [ ]:
churn_data['Churn'].value_counts()

0    2502
1    2498
Name: Churn, dtype: int64

In [ ]:
features = ['Day Mins', 'Day Charge', 'Eve Mins', 'Eve Charge', 'Night Mins', 'Night Charge', 'Intl Mins', 'Intl Charge', 'CustServ Calls']
target = 'Churn'

X = churn_data[features].values
y = churn_data[target].values
X.shape, y.shape

((5000, 9), (5000,))

In [ ]:
from sklearn.model_selection import train_test_split

X_train, X_valid, y_train, y_valid = train_test_split(X, y, test_size=0.25, random_state=0)

X_train.shape, X_valid.shape, y_train.shape, y_valid.shape

((3750, 9), (1250, 9), (3750,), (1250,))

In [ ]:
X_train

array([[13.23664371, 11.00768366,  5.54973717, ...,  6.12155121,
         3.12411923,  3.        ],
       [ 3.64623966,  4.11254353,  2.83378984, ...,  5.58227412,
         2.96599581,  7.        ],
       [ 0.53955568,  3.66313094,  0.08811627, ...,  4.46893939,
         1.29072559,  4.        ],
       ...,
       [10.40811761,  6.20244068,  7.00614012, ...,  4.32914583,
         4.21910436,  3.        ],
       [10.0109857 ,  7.35504399,  6.7736002 , ...,  3.69210465,
         6.18139625,  4.        ],
       [ 1.65060626,  4.23125228,  4.88634033, ...,  6.5126707 ,
         3.49669158,  5.        ]])

In [ ]:
y_train

array([1, 0, 0, ..., 1, 1, 0])

Consider whether you should normalize using:
https://keras.io/api/utils/python_utils/#normalize-function

In [ ]:
keras.utils.normalize(X_train)

array([[0.76923077, 0.30769231, 0.53846154, 0.15384615],
       [0.82813287, 0.50702013, 0.23660939, 0.03380134],
       [0.80642366, 0.5315065 , 0.25658935, 0.03665562],
       [0.76986879, 0.35413965, 0.5081134 , 0.15397376],
       [0.67054118, 0.34211284, 0.61580312, 0.23263673],
       [0.72965359, 0.28954508, 0.57909015, 0.22005426],
       [0.77530021, 0.28304611, 0.54147951, 0.15998258],
       [0.80033301, 0.56023311, 0.20808658, 0.04801998],
       [0.73659895, 0.33811099, 0.56754345, 0.14490471],
       [0.78889479, 0.55222635, 0.25244633, 0.09466737],
       [0.81120865, 0.55945424, 0.16783627, 0.02797271],
       [0.76185188, 0.34011245, 0.53057542, 0.14964948],
       [0.81609427, 0.5336001 , 0.21971769, 0.03138824],
       [0.67767924, 0.32715549, 0.59589036, 0.28041899],
       [0.79778206, 0.5424918 , 0.25529026, 0.06382256],
       [0.75911707, 0.3931142 , 0.48800383, 0.17622361],
       [0.70779525, 0.31850786, 0.60162596, 0.1887454 ],
       [0.76785726, 0.34902603,